#!/bin/bash
tools=/home/dan/tools
g++ -o find_2d_eigen -fopenmp -O3 2dresonator_complex_time.cpp uresonator.cpp sresonator.cpp bresonator.cpp -I${tools}/include -I${tools}/include/mesh1 -L${tools}/lib -lmesh1 -lsvg1 -lheds -Wl,-rpath=${tools}/lib
